// This file was generated by qtwaylandscanner
// source file is ext-background-effect-v1.xml

#include "qwayland-ext-background-effect-v1.h"

QT_BEGIN_NAMESPACE
QT_WARNING_PUSH
QT_WARNING_DISABLE_GCC("-Wmissing-field-initializers")

namespace QtWayland {

static inline void *wlRegistryBind(struct ::wl_registry *registry, uint32_t name, const struct ::wl_interface *interface, uint32_t version)
{
    const uint32_t bindOpCode = 0;
#if (WAYLAND_VERSION_MAJOR == 1 && WAYLAND_VERSION_MINOR > 10) || WAYLAND_VERSION_MAJOR > 1
    return (void *) wl_proxy_marshal_constructor_versioned((struct wl_proxy *) registry,
        bindOpCode, interface, version, name, interface->name, version, nullptr);
#else
    return (void *) wl_proxy_marshal_constructor((struct wl_proxy *) registry,
        bindOpCode, interface, name, interface->name, version, nullptr);
#endif
}

    ext_background_effect_manager_v1::ext_background_effect_manager_v1(struct ::wl_registry *registry, int id, int version)
    {
        init(registry, id, version);
    }

    ext_background_effect_manager_v1::ext_background_effect_manager_v1(struct ::ext_background_effect_manager_v1 *obj)
        : m_ext_background_effect_manager_v1(obj)
    {
        init_listener();
    }

    ext_background_effect_manager_v1::ext_background_effect_manager_v1()
        : m_ext_background_effect_manager_v1(nullptr)
    {
    }

    ext_background_effect_manager_v1::~ext_background_effect_manager_v1()
    {
    }

    void ext_background_effect_manager_v1::init(struct ::wl_registry *registry, int id, int version)
    {
        m_ext_background_effect_manager_v1 = static_cast<struct ::ext_background_effect_manager_v1 *>(wlRegistryBind(registry, id, &ext_background_effect_manager_v1_interface, version));
        init_listener();
    }

    void ext_background_effect_manager_v1::init(struct ::ext_background_effect_manager_v1 *obj)
    {
        m_ext_background_effect_manager_v1 = obj;
        init_listener();
    }

    ext_background_effect_manager_v1 *ext_background_effect_manager_v1::fromObject(struct ::ext_background_effect_manager_v1 *object)
    {
        if (wl_proxy_get_listener((struct ::wl_proxy *)object) != (void *)&m_ext_background_effect_manager_v1_listener)
            return nullptr;
        return static_cast<ext_background_effect_manager_v1 *>(ext_background_effect_manager_v1_get_user_data(object));
    }

    bool ext_background_effect_manager_v1::isInitialized() const
    {
        return m_ext_background_effect_manager_v1 != nullptr;
    }

    const struct wl_interface *ext_background_effect_manager_v1::interface()
    {
        return &::ext_background_effect_manager_v1_interface;
    }

    void ext_background_effect_manager_v1::destroy()
    {
        ext_background_effect_manager_v1_destroy(
            m_ext_background_effect_manager_v1);
        m_ext_background_effect_manager_v1 = nullptr;
    }

    struct ::ext_background_effect_surface_v1 *ext_background_effect_manager_v1::get_background_effect(struct ::wl_surface *surface)
    {
        return ext_background_effect_manager_v1_get_background_effect(
            m_ext_background_effect_manager_v1,
            surface);
    }

    void ext_background_effect_manager_v1::ext_background_effect_manager_v1_capabilities(uint32_t )
    {
    }

    void ext_background_effect_manager_v1::handle_capabilities(
        void *data,
        struct ::ext_background_effect_manager_v1 *object,
        uint32_t flags)
    {
        Q_UNUSED(object);
        static_cast<ext_background_effect_manager_v1 *>(data)->ext_background_effect_manager_v1_capabilities(
            flags);
    }

    const struct ext_background_effect_manager_v1_listener ext_background_effect_manager_v1::m_ext_background_effect_manager_v1_listener = {
        ext_background_effect_manager_v1::handle_capabilities,
    };

    void ext_background_effect_manager_v1::init_listener()
    {
        ext_background_effect_manager_v1_add_listener(m_ext_background_effect_manager_v1, &m_ext_background_effect_manager_v1_listener, this);
    }

    ext_background_effect_surface_v1::ext_background_effect_surface_v1(struct ::wl_registry *registry, int id, int version)
    {
        init(registry, id, version);
    }

    ext_background_effect_surface_v1::ext_background_effect_surface_v1(struct ::ext_background_effect_surface_v1 *obj)
        : m_ext_background_effect_surface_v1(obj)
    {
    }

    ext_background_effect_surface_v1::ext_background_effect_surface_v1()
        : m_ext_background_effect_surface_v1(nullptr)
    {
    }

    ext_background_effect_surface_v1::~ext_background_effect_surface_v1()
    {
    }

    void ext_background_effect_surface_v1::init(struct ::wl_registry *registry, int id, int version)
    {
        m_ext_background_effect_surface_v1 = static_cast<struct ::ext_background_effect_surface_v1 *>(wlRegistryBind(registry, id, &ext_background_effect_surface_v1_interface, version));
    }

    void ext_background_effect_surface_v1::init(struct ::ext_background_effect_surface_v1 *obj)
    {
        m_ext_background_effect_surface_v1 = obj;
    }

    ext_background_effect_surface_v1 *ext_background_effect_surface_v1::fromObject(struct ::ext_background_effect_surface_v1 *object)
    {
        return static_cast<ext_background_effect_surface_v1 *>(ext_background_effect_surface_v1_get_user_data(object));
    }

    bool ext_background_effect_surface_v1::isInitialized() const
    {
        return m_ext_background_effect_surface_v1 != nullptr;
    }

    const struct wl_interface *ext_background_effect_surface_v1::interface()
    {
        return &::ext_background_effect_surface_v1_interface;
    }

    void ext_background_effect_surface_v1::destroy()
    {
        ext_background_effect_surface_v1_destroy(
            m_ext_background_effect_surface_v1);
        m_ext_background_effect_surface_v1 = nullptr;
    }

    void ext_background_effect_surface_v1::set_blur_region(struct ::wl_region *region)
    {
        ext_background_effect_surface_v1_set_blur_region(
            m_ext_background_effect_surface_v1,
            region);
    }
}

QT_WARNING_POP
QT_END_NAMESPACE
